### ISSUE TITLE
tell me how to perform a 5 point?

### ISSUE THREAD

**Issue by visavi** [damige/linux-nvme#10]
tell me how to perform a 5 point?
Adjust your bootloader to boot linux-nvme

**Comment by damige** [comment]
To be able to help you i would have to know what bootloader you are currently using.

**Comment by visavi** [comment]
ubuntu 16.10 - grub
I understand gather under Ubuntu does not work, according to the instructions
makepkg team does not have a console

**Comment by damige** [comment]
Yes, these instructions and PKGBUILD are intended for Arch-Linux. I'm assuming it's possible to patch nvme on Ubuntu . You would need to patch a kernel of 4.7, 4.8, 4.9 or 4.10. I dont have a guide of how to do Ubuntu kernel patching, as i don't use it myself. 

Some options i see:
- Try to learn how to compile and patch kernels (for Ubuntu)
- Switch to an Arch-linux based distro so you can use my PKGBUILDs.

If above is to technical, or not desired:
- Wait for Ubuntu to use a new kernel that has this included (its not in 4.10 kernel, maybe its in 4.11 or later, which are not released yet)
