### ISSUE TITLE
Any thoughts on patching Ubuntu source?

### ISSUE THREAD

**Issue by phyxx** [damige/linux-nvme#12]
Hi,
I was trying to patch the Ubuntu 4.9.7 mainline source with the the provided files as suggested in the readme, APST.patch etc. Its not working though, it just gives 

'patch: **** Only garbage was found in the patch input.'

Maybe u got any thoughts regarding the issue. Thanks anyway and keep up the work.

cheers

**Comment by joel-wright** [comment]
I successfully patched the latest 4.10 Ubuntu kernel using the APST.patch in testing/4.10rc4

Well... I think it was successful... The patch applied cleanly and APSTE now seems to be enabled :)

**Comment by damige** [comment]
I have seen this happen when for example copy pasting from the webpage into nano.

Try to go here:
https://github.com/damige/linux-nvme/blob/master/src/4.9.8/APST.patch 
Rightclick RAW and save as.
Dont forget to do the same for the other 4.9.* patches.
Use the files you downloaded to patch the kernel

**Comment by phyxx** [comment]
Works like a charm now. Thanks for helping out :)

**Comment by damige** [comment]
No problem!
