### ISSUE TITLE
Continued prebuilt 4.9

### ISSUE THREAD

**Issue by sQVe** [damige/linux-nvme#14]
Firstly I would like to give a huge thank you for this kernel/project. It's made an big difference on my XPS 13 9360.

I'm wondering if you'll continue adding prebuilt version of kernel 4.9? My system's dmesg is screaming quite a bit from 4.10 so that's why I'm curious.

Cheers

**Comment by damige** [comment]
Hi and thanks sQVe, 
I am aware of the problem with dmesg, next patch (> 4.10.1-1) will reduce it.

Hope this answers your question

**Comment by damige** [comment]
4.10.1-2 has been released, dmesg should no longer be screaming. please let me know if its acceptable for you.

Best regards,

**Comment by sQVe** [comment]
@damige Dmesg is way more healthy but suspend/hibernate is still not working for me with 4.10.1-2...

**Comment by damige** [comment]
Just tried it and for me it works (and never had issues with it) do you have the same with stock arch kernel?

**Comment by sQVe** [comment]
@damige The stock arch kernel, linux, is currently at version 4.9.11. The problems does, probably, not lie in your patches. I've seen other people having problems with 4.10 and suspend/hibernate on the XPS 13 9360.

**Comment by damige** [comment]
The kernels i compile are stock except for the nvme patches. I have not included any special requests, reason being: to keep bugs to a minimum.

Are you the only person having issues with 4.10 and hibernation on the XPS 13 9360?  
If its a problem many people face with 4.10 i could consider compiling a 4.9 kernel once in a while if it helps. I have not been able to find sources suggesting this issue is widespread.

**Comment by damige** [comment]
Have you still a need for a precompiled 4.9? I may consider updating this once a while as its LTS

**Comment by sQVe** [comment]
@damige Currently I still do yes. Mainly because 4.10 only has around 80% success rate in resuming from supend / hibernate. I'm hoping this will change in later versions but 4.9 is running really good on my machine.

I actually did an PR a couple of minutes ago, adding some 4.9 sources. This is the same versions that I've been running since you dropped 4.9 support.
