### ISSUE TITLE
Where did the compiled kernels go?

### ISSUE THREAD

**Issue by plawucht** [damige/linux-nvme#3]
See Title.
Why did you decide to remove pkg?

**Comment by pinophyta** [comment]
Would be nice to have pre-compiled kernels back. Thanks!

**Comment by damige** [comment]
I ran out of space on GIT-LFS will see what i can do, any tips on cheap storage?

**Comment by plawucht** [comment]
One possibility is to upload the checksums for each version onto github with a download link to some one-click hoster like zippyshare. 
Alternatively, wouldn't it be possible to offer the package in the AUR as "linux-nvme-bin"?

**Comment by damige** [comment]
I have added back the compiled kernel section. incase it does not work for you, it may take up to 24h for DNS to update.
Regarding the binary package, i may be a waste of time as this might mainline in 4.10. I will consider this anyway.

**Comment by plawucht** [comment]
Thank you very very much! 
Until it will mainline, it won't be a waste of time, since you save many users computing time and power!

**Comment by damige** [comment]
I will look into it, but no eta yet.

**Comment by damige** [comment]
Just to let you know, i have made a repo you can add to your pacman.conf. Hope this helps.

**Comment by pinophyta** [comment]
It does! Thank you very much!
