### ISSUE TITLE
README.MD instruction

### ISSUE THREAD

**Issue by himanshu-dixit** [damige/linux-nvme#5]
Can you please add instruction to apply the patch in README.md.

**Comment by damige** [comment]
Hi, i have added some extra info in the readme.md.
Please let me know if its what you need.

**Comment by himanshu-dixit** [comment]
My config is XPS13 developer edition 9350, i tried to run makepkg and it prompted "Command not found".
I did install pacman by running apt install pacman.

**Comment by damige** [comment]
Judging by the fact that you use "apt" as a package manager i think you are running a debian based distribution. This package is only supported for arch based dirstributions and will not work on your system.

Options are to either patch the kernel yourself, or wait for this patch the be included in the mainline kernel. (Maybe 4.10, likely later)
