### ISSUE TITLE
How to check if powersaving is enabled?

### ISSUE THREAD

**Issue by HiFiJ** [damige/linux-nvme#6]
Hi, 

thanks very much for your efforts, reallay great! I'm on a XPS 9360 (3200x1800), and it's drawing 5.8 Watts idle on lowest screen backlight with Plasma 5.8.4, WiFi/BT on.
I see approx. 0.8 - 1 Watt decrease in power usage as shown in PowerTOP, so coming down to 4.8-5.0 W.
I' d just like to be sure APST is fully enabled. dmesg | grep psr gives me "Setting dangerous option enable_psr"  - is this the success message I want, or is there some other place like hdparm or lspci to check if it's enabled?

Thanks again very much,

Joost

**Comment by HiFiJ** [comment]
Btw, this is on patched kernel 4.9 on completely updated OpenSuse Tumbleweed.

**Comment by damige** [comment]
Hi PSR stands for Panel Self Refresh. It enables the graphics card to enter a lower power state. psr=1(link off) does not work in my device so i use the less effective psr=2(link-standby) Both are obviously better then psr=0. This has nothing to do with the NVME patch itself.

If "/sys/class/nvme/nvme0/power/pm_qos_latency_tolerance_us" exists it meens the device is capable and APST is enabled.
Also you can check it with "nvme get-feature -f 0x0c -H /dev/nvme0"
