### ISSUE TITLE
methodology behind

### ISSUE THREAD

**Issue by raki2322** [damige/linux-nvme#7]
hey hi,
Is there any research paper which describes the implementation details for the representation?

**Comment by damige** [comment]
Hi, as i am not the creator of this patch (just merely the maintainer of the PKGBUILD's for archlinux)
i must reference creator (Andy Lutomirski):
https://github.com/damige/linux-nvme/blob/master/src/4.9/APST.patch

If want more info regarding specifically APST then i dont have the sources. Maybe drop Andy a message?
