### ISSUE TITLE
Add "CONFIG_PCI_HOTPLUG=y" flag

### ISSUE THREAD

**Issue by plawucht** [damige/linux-nvme#8]
Hey! Thank you again very much for the service!
Would you please consider adding the `CONFIG_PCI_HOTPLUG=y` flag, so PCI hotplugging works as described here: https://wiki.archlinux.org/index.php/Dell_XPS_13_(9350)#Thunderbolt_3_.2F_USB_3.1

Kind regards and thanks in advance!

**Comment by damige** [comment]
hi, thanks for using it!
I gave it some thought and i would like to stay as close to stock+nvme as possible. (atleast for the AUR version, as it is being used by many different platforms)

However i have added your suggestion to: "https://github.com/damige/linux-nvme/tree/master/src/testing/intel-drm-nightly"
Please try that one and let me know if all is ok.

**Comment by plawucht** [comment]
It compiled without a hitch, it boots without a hitch. 
So far, it looks stable, idle battery power draw is between 4.3 and 6.6 watts. 
I added a boot flag forbidding the watchdog to start, because I have no use for it. Works fine so far, will so some testing with the WD15 dock and report back. 
You just added this line to the config and config.x86_64 file, right? No where else. So I can reproduce it in the future for all kernels, besides just the Intel drm nightly one.

**Comment by damige** [comment]
Yes, i just added the line to the config and config.x86_64. I currently use this kernel myself for testing. It's stable for me too.

**Comment by plawucht** [comment]
Well, I'm running the kernel for over a week now, and only had one hang with crash, caused by some unknown error, which I sadly can't reproduce. 
The hotplugging support maybe has done something, but the WD15 actually does not seem to dependent on this, the problems I encounter with it persist. It might be just because the WD15 is shit. :laughing: 

Overall, I can't really find a reason why it shouldn't be in the standard config, I'll personally will stick with it, maybe one day I'll encounter a proper Thunderbolt 3 driven device and can instantly use it. 

For me, this "issue" is solved.
