### ISSUE TITLE
Battery tweaks

### ISSUE THREAD

**Issue by andre0xFF** [damige/linux-nvme#9]
Hey. I checked the benchmarks file and wanted to ask how are you getting around 5~3w? I get around 10w with fedora 25 and tlp installed, this translates to 3 hours tops of usage. I have the same 9350 as you. Mind to share your tweaks?

**Comment by damige** [comment]
Even without any tweaks im getting better then 10w! (maybe distro related?)

In any case here are my kernel options: 
"pcie_aspm=force i915.modeset=1 i915.enable_psr=2 i915.enable_rc6=7 i915.enable_fbc=1 i915.semaphores=1 i915.lvds_downclock=1 i915.enable_guc_loading=1 i915.enable_guc_submission=1"

I have also installed TLP for power optimisations.

**Comment by andre0xFF** [comment]
The min I can get is 8w with tlp and the same parameters. Why is there such a big difference? I browsed the arch forum and there are some people that can get below 3w.

**Comment by damige** [comment]
You will be able to shave off ~1w (up to 1.5w) when idle if you use the nvme patches supplied here. You would have to compile it into fedora yourself though, as i only support Arch. (Maybe someone is doing the same over at the fedora community?)

This should get you to 6.5-7watt, which can be normal depending on how you test. My tests are done with wifi connected and lowest possible brightness with NO programs open, running plasma desktop. 
With max brightness and a few programs running ~7 watt avg is quite normal.
When you see very low power usage these people are not running any DE. So this is not a realistic scenario.
